##########################################################
# 3_funnel_plot_limits_data.R
# Thomas Godfrey
# 16/04/2019
# Script 3
# Data preparation for export
# Written/run on R Studio desktop (uses //PHI_conf/)
# R version 3.5.1 
# This script creates CI data for funnel plots in Excel
# Transcribed from SPSS script "2_KPI_graphs_limits_N18.sps"
# At:
##########################################################

### Purpose of script
# Script 2 generates 'KPI data.xlsx' containing KPI results for KPIs 1-26 by HB.
# For KPIs 3,7,8,17,19 and 20, we use funnel plots to check HB results are within
#     acceptable warning limits (95% CIs) and control limits (99% CIs).
# For a given KPI, funnel plots consist of the KPI result per HB (y-axis co-ordinate), 
# plotted against the denominator for that health board (x-axis co-ordinate),
# along with warning/control limits for Scotland, for different values of the denominator.

# This script has two purposes:
# 1. to export relevant KPI denominator values to provide the x-axis values 
#     needed to plot HB datapoints on funnel plots (with actual HB KPI estimates 
#     (y-axis values) available from 'KPI data.xlsx')
# 2. to generate a dataset, for each KPI, of 95% and 99% confidence intervals, 
#     using Scotland-level KPI standard errors, and a series of values of the 
#     KPI denominator. These datasets of upper and lower CIs then provide
#     the x- and y-axis co-ordinates for plotting warning and control limits.


### Notes: 
## KPIs with funnel plots:
# 3. % of people with a positive screening test result for both sexes, by HB.
# 7. % of colonoscopic complications, by HB.
# 8. % of people that had a cancer detected for both sexes, by HB.
#17. % of people that had a polyp cancer detected for both sexes, by HB.
#19. % of people with adenomas detected for both sexes, by HB.
#20. % of people with high risk adenomas detected for both sexes, by HB.

## Hence, the two sets of KPI denminator values required are:
# the Number of people with a completed screening test result (for KPIs 3,8,17,19,20)
# the Number of people who have had a colonoscopy performed (for KPI 7)


### Key outputs
# 1. no.of people who completed kits with a final result by HB (x-axis)
# 2. no.of people with a positive result who have a colonoscopy by HB (x-axis)
# 3. Wilson Score confidence intervals for funnel plot limits for each KPI (x- & y-axis) 
#Note: Outputs generated by this syntax are copied into the KPI report Excel file,
#       an then 'hidden' but used to generate charts. 


### Step 1: Housekeeping

##Load packages
#install.packages("tidyverse")

library(magrittr)
library(dplyr)
library(tidyr)
library(lubridate)
library(haven)
library(readxl)
library(janitor)
library(binom)
library(tidyverse)


### Define two-year reporting period: 
#1 May 2016 to 30 April 2018
start_period <- "2016-05-01"
end_period   <- "2018-04-30"



### Step 2: Bring in analysis database from script 1 and then filter data.
analysis_db <- readRDS(paste0("/PHI_conf/CancerGroup1/Topics/BowelScreening/",
                              "TPP/KPIs/Code + DB/analysis_dataset.rds"))
dim(analysis_db)

# Use Select statement to keep only required variables
names(analysis_db)
[1] "chinum"         "invdate"        "sex"            "screres"        "haemoglobin"    "screresdate"   
[7] "date_round"     "hbres14"        "simd2009"       "simd2012"       "simd2016"       "age"           
[13] "age_group"      "optin"          "screresdat"     "dateprecol"     "coloffered"     "datecoloff"    
[19] "colperf"        "datecolperf"    "colreason"      "colcomp"        "cancer"         "icd10"         
[25] "tnmt"           "tnmn"           "tnmm"           "dukes"          "adenoma"        "adenno"        
[31] "adensize"       "polypca"        "complicp"       "hbr14"          "invite_n"       "uptake_n"      
[37] "positive_n"     "col_perf_n"     "col_complete_n" "col_complic_n"  "cancer_n"       "polyp_cancer_n"
[43] "adenoma_n"      "lr_adenoma_n"   "ir_adenoma_n"   "hr_adenoma_n"   "date_diff"      "waiting_time"  
[49] "dukes_der"      "uptake_rnd_1"   "uptake_rnd_2"   "uptake_rnd_3"   "uptake_rnd_4"   "uptake_rnd_5"  
[55] "uptake_rnd_6"   "uptake_history"


slim_db <- analysis_db %>%
  select(analysis_db, invdate, sex, screres )

slim_db <- analysis_db %>%
  select(analysis_db, 
         c('invdate', 'sex', 'hbr14', 
           'invite_n', 'uptake_n', 'col_perf_n', 'positive_n', 'polyp_cancer_n', 'adenoma_n',
           'hr_adenoma_n'))
dim(slim_db)


# Use Filter statement to keep only data from report period
analysis_db <- analysis_db %>%
  filter(invdate >= as.Date(start_period) & invdate <= as.Date(end_period)) %>%
  filter(optin == 0) %>%
  filter(hbr14 %in% 1:14)

dim(analysis_db)
str(analysis_db)


## Step 2: Calculate HB-level KPI denominator values for x-axis co-ordinates i.e.:
# the number of people who completed kits with a final result
# the number of people with positive result having a colonoscopy performed
denom_n_hb <- analysis_db %>%
  group_by(hbr14) %>%
  summarise(
    uptake_n = sum(uptake_n),
    col_perf_n = sum(col_perf_n)
  )

# export

# Calculate Scotland level values for each KPI (3,7,8,17,19,20)
scot_p <- analysis_db %>%
  summarise(
    positive_p = sum(positive_n)/sum(uptake_n),
    col_complic_p = sum(col_complic_n)/sum(col_perf_n),
    cancer_p = sum(cancer_n)/sum(uptake_n),
    polyp_cancer_p = sum(polyp_cancer_n)/sum(uptake_n),
    adenoma_p = sum(adenoma_n)/sum(uptake_n),
    hr_adenoma_p = sum(hr_adenoma_n)/sum(uptake_n)
  )
# export?

## Step 3: Calculate Wilson Score confidence limits (intervals).

#What does SPSS syntax do?
# Gets Scotland-level rates by KPI, Index1(==3 i.e. rates) and sex(==3 all persons)
# Matches them to a skeleton of KPI, Index1(==3), sex (==3) and 'n' BY KPI Index1 & SEX.
# (n= 1-250,000 but in no apperent logical order)
# Essentially adding Scotland-level values/rates for each KPI to each value of 'n'.
# Back covert rates back from % to proportion
# Compute lower and upper 95% and 99% CIs
# Convert back to a %

# Create skeleton
# Get Scotland KPI data from 'KPI data.xlsx' or its equivalent
# Match them to add rates to skeleton.
# Calculate CIs
# Export

## Create skeleton
# KPI: 3,7,8,17,19,20
# Sex: 3
# n:
KPI <- c(3,7,8,17,19,20)
sex <- 3
n <- c(1, 
       seq(10, 50,  by=10),
       seq(100, 2000, by=50),
       seq(2100, 2300, by=100),
       seq(2500, 10000, by=500),
       seq(11000, 19000, by=1000),
       seq(22000, 250000,  by=3000))

skeleton <- crossing(KPI,sex,n)


# Get Scotland KPI data from 'KPI data.xlsx' or its equivalent
Scotland_KPIs_db <- read_excel(paste0("/PHI_conf/CancerGroup1/Topics/BowelScreening/",
                                      "TPP/KPIs/Code + DB/Data/KPI_data.xlsx"))

dim(Scotland_KPIs_db)
names(Scotland_KPIs_db)

Scotland_KPIs_db <- select(Scotland_KPIs_db, KPI, sex, "15") %>%
  filter(sex == 3) %>%
  filter(KPI %in% c(3,7,8,17,19,20))

# Match them to add rates to skeleton.

test.db <- left_join(skeleton, Scotland_KPIs_db, by = c("KPI","sex"))


#### Calculate CIs

test.db$p <- (test.db$`15`)/100


test.db$lower95 <- 
  
  
  
  
  test.db$p + 
  
  (2*test.db$p + qnorm(0.975)^2 - qnorm(0.975)*(sqrt(qnorm(0.975)^2 + (4*test.db$p*(1-test.db$p))) / 2*(test.db$n + qnorm(0.975)^2)))

((p+idf.chisq(1-alpha,1)/(2*n)-idf.normal(1-(alpha/2),0,1)*sqrt((p*(1-p)+idf.chisq(1-alpha,1)/(4*n))/n))) / (1+idf.chisq(1-alpha,1)/n).






lower95CL=
  
  
  
  
  test.db$lower95 <- (2*test.db$p + qnorm(0.975)^2 - qnorm(0.975)*(sqrt(qnorm(0.975)^2 + (4*test.db$p*(1-test.db$p))) / 2*(test.db$n + qnorm(0.975)^2)))

test.db$upper95 <- test.db$p + (qnorm(0.975)*sqrt((1/test.db$n)*test.db$p*(1-test.db$p)))
p + c(-qnorm(0.975),qnorm(0.975))*sqrt((1/1000)*p*(1-p))
[1] 0.4890345 0.5509655


lower95CL=((p+idf.chisq(1-alpha,1)/(2*n)-idf.normal(1-(alpha/2),0,1)*sqrt((p*(1-p)+idf.chisq(1-alpha,1)/(4*n))/n))) / (1+idf.chisq(1-alpha,1)/n).

CI.file <-binconf(data.extract5$participants, data.extract5$invitees, alpha=0.05,
                  method=c("wilson"),
                  include.x=TRUE, include.n=TRUE, return.df=TRUE)




install.packages('Hmisc')
library(Hmisc)

??binconf
binconf(0:10,10,include.x=TRUE,include.n=TRUE)
binconf(46,50,method="all")



test.db$successes <-  test.db 
CIfile <- binom.confint(test.db$x, uptake_summary$n, 
                        conf.level=0.95, methods=c("wilson"))

??binom.confint
CI.file <-binconf(data.extract5$participants, data.extract5$invitees, alpha=0.05,
                  method=c("wilson"),
                  include.x=TRUE, include.n=TRUE, return.df=TRUE)



### Old code
CI.file <-binconf(data.extract5$participants, data.extract5$invitees, alpha=0.05,
                  method=c("wilson"),
                  include.x=TRUE, include.n=TRUE, return.df=TRUE)

#Conver to percentages
CI.file$LowerCI<- CI.file$Lower*100
CI.file$UpperCI <- CI.file$Upper*100

# Merge
names(CI.file)[2] <- "invitees"
CI.file$invitees <- as.integer(CI.file$invitees)
data.extract6 <- merge(data.extract5, CI.file,by="invitees")

data.extract7 <- data.extract6[,c("hbr14", "invitees", "participants", "percent.uptake","LowerCI","UpperCI")]

data.extract8 <- data.extract7[order(data.extract7$hbr14, decreasing = F),]

### Gavin code
## Add confidence intervals
## Question for Jack - how are confidence intervals done in the tidyverse/within TPP? Found some information
## with broom but not that helpful at a glance

# Use Wilson Score confidence intervals
uptake_summary_conf <- binom.confint(uptake_summary$x, uptake_summary$n, 
                                     conf.level=0.95, methods=c("wilson")) %>%
  # add in health board names
  mutate(geography = c("Ayrshire and Arran",
                       "Borders",
                       "Dumfries and Galloway",
                       "Fife",
                       "Forth Valley",
                       "Grampian",
                       "Greater Glasgow and Clyde",
                       "Highland",
                       "Lanarkshire",
                       "Lothian",
                       "Orkney",
                       "Shetland",
                       "Tayside",
                       "Western Isles",
                       "All Scotland")) %>%
  # rename and rearrange columns for output
  rename(uptake_n = x, invited_n = n, uptake_rate = mean) %>%
  select(geography, uptake_rate, lower, upper) %>%
  # Multiply proportions by 100 to give percentages
  # This has been the convention for bowel screening percentages, not
  # set in stone for it to be done this way
  mutate(uptake_rate = uptake_rate * 100) %>%
  mutate(lower = lower * 100) %>%
  mutate(upper = upper * 100)

# Export